title: "Yue Li"
author: "Yue Li"
description: "University of Pennsylvania"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: False        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: True        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Lab", url: "https://picsl.upenn.edu/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yue.li@pennmedicine.upenn.edu"}
  - {title: Github, icon: github, url: "https://github.com/liyue3780"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
